spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hansocial
    username: eren
    password: hancagiz
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
